INSERT INTO Persons (name, surname, age, city_of_living, phone_number) VALUES
                                                                           ('Alice', 'Smith', 25, 'New York', '12345678'),
                                                                           ('Bob', 'Johnson', 30, 'Los Angeles', '98765432'),
                                                                           ('Charlie', 'Brown', 22, 'Chicago', '55512345'),
                                                                           ('David', 'Lee', 28, 'San Francisco', '77788899'),
                                                                           ('Emma', 'Davis', 35, 'Boston', '11122233'),
                                                                           ('Frank', 'Wilson', 40, 'Seattle', '44455566'),
                                                                           ('Grace', 'Martinez', 27, 'Miami', '99988877'),
                                                                           ('Henry', 'Garcia', 33, 'Dallas', '66655544'),
                                                                           ('Ivy', 'Lopez', 29, 'Houston', '22233344'),
                                                                           ('Jack', 'Perez', 26, 'Phoenix', '33344455'),
                                                                           ('Kevin', 'Nguyen', 31, 'Philadelphia', '88899900'),
                                                                           ('Lily', 'Patel', 37, 'Atlanta', '55566677'),
                                                                           ('Mike', 'Kim', 34, 'Denver', '77766655'),
                                                                           ('Nancy', 'Singh', 23, 'Detroit', '12312314'),
                                                                           ('Oliver', 'Chen', 32, 'Las Vegas', '99900011'),
                                                                           ('Peter', 'Wang', 38, 'San Diego', '44433222'),
                                                                           ('Queenie', 'Gonzalez', 36, 'Portland', '88776666'),
                                                                           ('Robert', 'Liu', 24, 'New Orleans', '55544333'),
                                                                           ('Sarah', 'Chang', 39, 'Minneapolis', '22210000'),
                                                                           ('Tom', 'Ramirez', 21, 'Salt Lake City', '67778888');